### ISSUE TITLE
могло бы быть и хуже:)

### ISSUE THREAD

**Issue by danilaeremin** [dino-mayk/GoToHome#18]
1) форма сжата по центру
![image](https://user-images.githubusercontent.com/10955928/209306116-ba278e4a-0d86-48dd-abab-4bd615d32877.png)
2) как я должен догадаться, что надо прокрутить вниз? у меня на первом экране на 27 дюймах только котик
![image](https://user-images.githubusercontent.com/10955928/209306184-6fed7625-34fb-401c-9c8e-2df396ec1ec5.png)
3) в репозиторий зачем-то попал кэш
4) зачем мы храни закомментированный код?
`# dotenv_path = join(dirname(__file__), '.env')`
5) тесты хоть и есть, но они ни о чем
6) зачем тут Q? почему просто filter не угодил?
![image](https://user-images.githubusercontent.com/10955928/209306792-7c26635a-6946-482f-b951-445ad913b684.png)
7) а имя `i` тут точно уместное?
![image](https://user-images.githubusercontent.com/10955928/209306887-aecf1abb-2dd2-4426-a530-31692fafda09.png)
8) verbose_name и автокапитализация в моделях:)
9) типы животных захардкожены... и их всего три... кошка, собака и другое... грусть
10) в add_post много бойлерплейта, который пропадет при использовании CBV
11) а зачем тут пустая строка?
![image](https://user-images.githubusercontent.com/10955928/209307312-8d6fc05c-23a6-4245-aec9-abbfdaf56cdd.png)
12) форматирование шаблонов... всё плохо:(
13) ошибки валидации HTML
14) а точно все зависимости нужны?
15) дважды игнорируем миграции
![image](https://user-images.githubusercontent.com/10955928/209307673-494de869-de54-40c0-bad0-6bece5536c3b.png)

**Comment by dino-mayk** [comment]
Понял, спасибо за ревью, а какая оценка?
