### ISSUE TITLE
Почему-то CI/CD не запускается...

### ISSUE THREAD

**Issue by danilaeremin** [dino-mayk/GoToHome#9]

**Comment by dino-mayk** [comment]
![изображение](https://user-images.githubusercontent.com/94930027/208442003-bc10cdbe-02d4-4267-b2db-cacb5437f95f.png)
Теперь запускаются

**Comment by danilaeremin** [comment]
Кажется закрывать можно будет тогда, когда плашка будет зеленая:) пока тесты падают

**Comment by dino-mayk** [comment]
Счастье это -
![изображение](https://user-images.githubusercontent.com/94930027/209149287-8a2bad5f-391a-45f3-a4b5-9a3ecccc0cc2.png)
